#!/bin/bash
set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${GREEN}=== WG-Easy + 3x-ui + Traefik Deployment ===${NC}"
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}Please run as root (sudo ./deploy.sh)${NC}"
    exit 1
fi

# Check if Docker is installed
if ! command -v docker &> /dev/null; then
    echo -e "${YELLOW}Docker not found. Installing...${NC}"
    curl -sSL https://get.docker.com | sh
    systemctl enable docker
    systemctl start docker
    echo -e "${GREEN}Docker installed successfully${NC}"
    echo ""
fi

# Function to prompt for input with default value
prompt_with_default() {
    local prompt="$1"
    local default="$2"
    local var_name="$3"
    local is_secret="$4"

    if [ -n "$default" ]; then
        echo -en "${CYAN}$prompt${NC} [${default}]: "
    else
        echo -en "${CYAN}$prompt${NC}: "
    fi

    if [ "$is_secret" = "true" ]; then
        read -s value
        echo ""
    else
        read value
    fi

    if [ -z "$value" ]; then
        value="$default"
    fi

    eval "$var_name='$value'"
}

# Function to generate random password
generate_password() {
    tr -dc 'A-Za-z0-9_-' </dev/urandom | head -c 20
}

# Configuration wizard
configure() {
    echo -e "${GREEN}Configuration Wizard${NC}"
    echo -e "Press Enter to accept default values in [brackets]"
    echo ""

    # Domain
    prompt_with_default "Enter your domain (e.g., vpn.example.com)" "${DOMAIN:-}" "DOMAIN"
    while [ -z "$DOMAIN" ]; do
        echo -e "${RED}Domain is required!${NC}"
        prompt_with_default "Enter your domain" "" "DOMAIN"
    done

    # Email for Let's Encrypt
    prompt_with_default "Enter email for SSL certificates" "${ACME_EMAIL:-}" "ACME_EMAIL"
    while [ -z "$ACME_EMAIL" ]; do
        echo -e "${RED}Email is required for Let's Encrypt!${NC}"
        prompt_with_default "Enter email for SSL certificates" "" "ACME_EMAIL"
    done

    # Admin username
    prompt_with_default "Admin username" "${INIT_USERNAME:-admin}" "INIT_USERNAME"

    # Admin password
    if [ -n "$INIT_PASSWORD" ]; then
        echo -e "${CYAN}Admin password${NC} [keep current]: "
        echo -en "  Press Enter to keep current or enter new password: "
        read -s new_password
        echo ""
        if [ -n "$new_password" ]; then
            INIT_PASSWORD="$new_password"
            echo -e "${GREEN}Password updated${NC}"
        else
            echo -e "${YELLOW}Keeping current password${NC}"
        fi
    else
        local default_pass=$(generate_password)
        echo -e "${CYAN}Admin password${NC} [auto-generate]: "
        echo -en "  Enter password or press Enter for: ${YELLOW}${default_pass}${NC}: "
        read -s INIT_PASSWORD
        echo ""
        if [ -z "$INIT_PASSWORD" ]; then
            INIT_PASSWORD="$default_pass"
            echo -e "${YELLOW}Using generated password: ${INIT_PASSWORD}${NC}"
            echo -e "${RED}Save this password! It won't be shown again.${NC}"
        fi
    fi

    # WireGuard port
    prompt_with_default "WireGuard UDP port" "${WG_PORT:-51820}" "WG_PORT"

    # DNS servers
    prompt_with_default "DNS servers for VPN clients" "${INIT_DNS:-1.1.1.1, 8.8.8.8}" "INIT_DNS"

    # VPN subnet
    prompt_with_default "VPN IPv4 subnet" "${INIT_IPV4_CIDR:-10.8.0.0/24}" "INIT_IPV4_CIDR"

    # Allowed IPs
    echo ""
    echo -e "${CYAN}Traffic routing mode:${NC}"
    echo "  1) Full tunnel - all traffic through VPN"
    echo "  2) Split tunnel - only VPN subnet traffic"

    # Determine current mode
    local current_mode="1"
    if [ -n "$INIT_ALLOWED_IPS" ] && [ "$INIT_ALLOWED_IPS" != "0.0.0.0/0, ::/0" ]; then
        current_mode="2"
    fi

    prompt_with_default "Choose option" "$current_mode" "TUNNEL_MODE"

    if [ "$TUNNEL_MODE" = "2" ]; then
        INIT_ALLOWED_IPS="${INIT_IPV4_CIDR//x/0}"
    else
        INIT_ALLOWED_IPS="0.0.0.0/0, ::/0"
    fi

    # IPv6
    echo ""
    local ipv6_default="yes"
    if [ "$DISABLE_IPV6" = "true" ]; then
        ipv6_default="no"
    fi
    prompt_with_default "Enable IPv6 support? (yes/no)" "$ipv6_default" "IPV6_CHOICE"
    if [ "$IPV6_CHOICE" = "no" ] || [ "$IPV6_CHOICE" = "n" ]; then
        DISABLE_IPV6="true"
        INIT_IPV6_CIDR=""
    else
        DISABLE_IPV6="false"
        INIT_IPV6_CIDR="${INIT_IPV6_CIDR:-fdcc:ad94:bacf:61a3::/64}"
    fi

    # Write .env file
    echo ""
    echo -e "${YELLOW}Saving configuration...${NC}"

    cat > .env << 'ENVFILE'
# WG-Easy + Traefik Configuration
# Generated by deploy.sh

ENVFILE
    echo "DOMAIN='${DOMAIN}'" >> .env
    echo "ACME_EMAIL='${ACME_EMAIL}'" >> .env
    echo "INIT_USERNAME='${INIT_USERNAME}'" >> .env
    echo "INIT_PASSWORD='${INIT_PASSWORD//\'/\'\\\'\'}'" >> .env
    echo "WG_PORT='${WG_PORT}'" >> .env
    echo "INIT_DNS='${INIT_DNS}'" >> .env
    echo "INIT_IPV4_CIDR='${INIT_IPV4_CIDR}'" >> .env
    echo "INIT_IPV6_CIDR='${INIT_IPV6_CIDR}'" >> .env
    echo "INIT_ALLOWED_IPS='${INIT_ALLOWED_IPS}'" >> .env
    echo "DISABLE_IPV6='${DISABLE_IPV6}'" >> .env
    echo "INIT_ENABLED='true'" >> .env

    chmod 600 .env
    echo -e "${GREEN}Configuration saved to .env${NC}"
}

# Check if .env exists
if [ -f .env ]; then
    source .env
    echo -e "${YELLOW}Existing configuration found.${NC}"
    echo -e "  Domain:   ${DOMAIN}"
    echo -e "  Username: ${INIT_USERNAME}"
    echo ""
    prompt_with_default "Reconfigure? (yes/no)" "no" "RECONFIG"
    if [ "$RECONFIG" = "yes" ] || [ "$RECONFIG" = "y" ]; then
        configure
    fi
else
    configure
fi

source .env

echo ""

# Validate configuration
if [ -z "$DOMAIN" ]; then
    echo -e "${RED}Error: DOMAIN is not set${NC}"
    exit 1
fi

if [ -z "$ACME_EMAIL" ]; then
    echo -e "${RED}Error: ACME_EMAIL is not set${NC}"
    exit 1
fi

if [ -z "$INIT_PASSWORD" ]; then
    echo -e "${RED}Error: INIT_PASSWORD is not set${NC}"
    exit 1
fi

# Open firewall ports if ufw is installed
if command -v ufw &> /dev/null; then
    echo -e "${YELLOW}Configuring firewall (ufw)...${NC}"
    ufw allow 80/tcp comment "HTTP (for Let's Encrypt)" >/dev/null 2>&1
    ufw allow 443/tcp comment "Xray Reality + HTTPS (via fallback to Traefik)" >/dev/null 2>&1
    ufw allow 15672/tcp comment "3x-ui Panel" >/dev/null 2>&1
    ufw allow ${WG_PORT:-51820}/udp comment "WireGuard" >/dev/null 2>&1
    echo -e "${GREEN}Firewall configured${NC}"
fi

# Start the service
echo -e "${YELLOW}Starting services...${NC}"
docker compose up -d

echo ""
echo -e "${GREEN}╔════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║       Deployment Complete!                 ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  ${CYAN}WG-Easy UI:${NC}   https://${DOMAIN}"
echo -e "  ${CYAN}Username:${NC}     ${INIT_USERNAME:-admin}"
echo -e "  ${CYAN}Password:${NC}     (saved in .env)"
echo ""
echo -e "  ${CYAN}3x-ui Panel:${NC}  https://${DOMAIN}:15672"
echo -e "  ${CYAN}3x-ui Login:${NC}  admin / admin ${RED}(change immediately!)${NC}"
echo ""
echo -e "  ${CYAN}WireGuard:${NC}    ${DOMAIN}:${WG_PORT:-51820}/udp"
echo ""
echo -e "${YELLOW}Note:${NC} SSL certificate will be issued automatically."
echo "First request may take a few seconds."
echo ""
echo -e "${CYAN}Commands:${NC}"
echo "  View logs:     docker compose logs -f"
echo "  Stop:          docker compose down"
echo "  Restart:       docker compose up -d"
echo "  Reconfigure:   sudo ./deploy.sh"
